name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Update to latest stable version

      - name: Use Node.js 18  # Update to a stable LTS version (16 is outdated)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (clean install)
        run: npm ci  # More reliable than 'npm install' for CI

      - name: Install Chrome for Headless Tests
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Test
        run: npm test -- --watch=false --browsers=ChromeHeadless
